pipeline {
    agent any

    stages {
        stage('CI - Lint') {
            agent {
                docker { image 'maven:3.8.6-openjdk-11-slim' }
            }
            steps {
                sh 'apt-get update && apt-get install -y make'
                sh 'make lint'
            }
        }

        stage('CI - Test') {
            agent {
                docker { image 'maven:3.8.6-openjdk-11-slim' }
            }
            steps {
                sh 'apt-get update && apt-get install -y make'
                sh 'make test'
            }
        }

        stage('CI - Docker Build') {
            steps {
                sh 'docker build -t devops-java-app -f devops/Dockerfile .'
            }
        }

        stage('CD - Deploy') {
            when {
                anyOf {
                    branch 'develop'
                    branch 'master'
                }
            }
            steps {
                sh 'docker compose -f docker-compose.yml up -d'
                sh 'sleep 20'
                sh 'docker compose -f docker-compose.yml exec -T app curl -f http://localhost:8080/hello || true'
                sh 'docker compose -f docker-compose.yml down --volumes'
            }
        }
    }
}